// MOVIES
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
export const RECEIVE_HARDCODED_MOVIES = 'RECEIVE_HARDCODED_MOVIES';

// SEARCH
export const SEARCH_MOVIE = 'SEARCH_MOVIE';

